ALTER TABLE category
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE payment
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE budget
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
